const characters = [
    // Row 0
    { type: "blank" },
    { type: "blank" },
    { type: "unit", name: "Kyupita", src: "units/Kyupita.png" },
    { type: "blank" },
    { type: "unit", name: "Teotoratta", src: "units/Teotoratta.png" },
    { type: "blank" },
    { type: "unit", name: "Alicianrone", src: "units/Alicianrone.png" },
    { type: "blank" },
    { type: "unit", name: "Chris", src: "units/Chris.png" },
    { type: "blank" },
    // Row 1
    { type: "blank" },
    { type: "blank" },
    { type: "unit", name: "QP (Dangerous)", src: "units/QP (Dangerous).png" },
    { type: "unit", name: "Tomato & Mimyuu", src: "units/Tomato Mimyuu.png" },
    { type: "unit", name: "Ceoreparque", src: "units/Ceoreparque.png" },
    { type: "unit", name: "Miusaki", src: "units/Miusaki.png" },
    { type: "unit", name: "Yuki (Dangerous)", src: "units/Yuki (Dangerous).png" },
    { type: "unit", name: "Yuuki", src: "units/Yuuki.png" },
    { type: "blank" },
    { type: "blank" },
    // Row 2
    { type: "blank" },
    { type: "unit", name: "Hime (Moonlight)", src: "units/Hime (Moonlight).png" },
    { type: "unit", name: "Suguri (Ver.2)", src: "units/Suguri (Ver.2).png" },
    { type: "unit", name: "QP", src: "units/QP.png" },
    { type: "unit", name: "Store Manager", src: "units/Store Manager.png" },
    { type: "unit", name: "Sweet Breaker", src: "units/Sweet Breaker Amami.png" },
    { type: "unit", name: "Syura", src: "units/Syura.png" },
    { type: "unit", name: "Yuki", src: "units/Yuki.png" },
    { type: "unit", name: "Cuties (Sora & Sham)", src: "units/Cuties Sora Sham.png" },
    { type: "blank" },
    // Row 3
    { type: "blank" },
    { type: "unit", name: "Suguri (46 Billion Years)", src: "units/Suguri (46 Billion Years) Suguri Boomer.png" },
    { type: "unit", name: "Suguri", src: "units/Suguri.png" },
    { type: "unit", name: "Kyousuke", src: "units/Kyousuke.png" },
    { type: "unit", name: "Mei", src: "units/Mei.png" },
    { type: "unit", name: "Natsumi", src: "units/Natsumi.png" },
    { type: "unit", name: "Nico", src: "units/Nico.png" },
    { type: "unit", name: "Star Breaker", src: "units/Star Breaker Starbo Reika.png" },
    { type: "blank" },
    { type: "blank" },
    // Row 4
    { type: "blank" },
    { type: "blank" },
    { type: "unit", name: "Shifu Robot", src: "units/Shifu Robot.png" },
    { type: "unit", name: "Saki", src: "units/Saki.png" },
    { type: "unit", name: "Chicken", src: "units/Chicken Haruo.png" },
    { type: "unit", name: "Kiriko", src: "units/Kiriko.png" },
    { type: "unit", name: "Krilalaris", src: "units/Krilalaris.png" },
    { type: "unit", name: "Sora", src: "units/Sora.png" },
    { type: "unit", name: "Tsih", src: "units/Tsih.png" },
    { type: "blank" },
    // Row 5
    { type: "unit", name: "Halena", src: "units/Halena.png" },
    { type: "unit", name: "Sumika", src: "units/Sumika.png" },
    { type: "unit", name: "Robo Ball", src: "units/Robo Ball Roboball.png" },
    { type: "unit", name: "NoName", src: "units/NoName Noname.png" },
    { type: "unit", name: "Aru (Scramble)", src: "units/Aru (Scramble).png" },
    { type: "unit", name: "Arthur", src: "units/Arthur.png" },
    { type: "unit", name: "Nath", src: "units/Nath.png" },
    { type: "unit", name: "Sora (Military)", src: "units/Sora (Military).png" },
    { type: "blank" },
    { type: "blank" },
    // Row 6
    { type: "blank" },
    { type: "unit", name: "Maynie", src: "units/Maynie.png" },
    { type: "unit", name: "Mio", src: "units/Mio.png" },
    { type: "unit", name: "Nanako", src: "units/Nanako.png" },
    { type: "unit", name: "Kyoko", src: "units/Kyoko.png" },
    { type: "unit", name: "Aru", src: "units/Aru.png" },
    { type: "unit", name: "Mira", src: "units/Mira.png" },
    { type: "unit", name: "Sham", src: "units/Sham.png" },
    { type: "unit", name: "Islay", src: "units/Islay.png" },
    { type: "unit", name: "Fernet (Noble)", src: "units/Fernet (Noble).png" },
    // Row 7
    { type: "unit", name: "Cook", src: "units/Cook Chicken.png" },
    { type: "unit", name: "Ellie", src: "units/Ellie.png" },
    { type: "unit", name: "Tomomo", src: "units/Tomomo.png" },
    { type: "unit", name: "Kae", src: "units/Kae.png" },
    { type: "unit", name: "Iru", src: "units/Iru.png" },
    { type: "unit", name: "Alte", src: "units/Alte.png" },
    { type: "unit", name: "Fernet", src: "units/Fernet.png" },
    { type: "unit", name: "Sherry", src: "units/Sherry.png" },
    { type: "unit", name: "Tequilla", src: "units/Tequilla.png" },
    { type: "blank" },
    // Row 8
    { type: "blank" },
    { type: "unit", name: "Arnelle", src: "units/Arnelle.png" },
    { type: "unit", name: "Tomomo (Casual)", src: "units/Tomomo (Casual) Tomomo (Sweet Eater).png" },
    { type: "unit", name: "Marie Poppo", src: "units/Marie Poppo.png" },
    { type: "unit", name: "Hime", src: "units/Hime.png" },
    { type: "ui", name: "Random", src: "units/Random.png", link: "https://100orangejuice.fandom.com/wiki/Special:Random", class: "random" },
    { type: "unit", name: "Marc", src: "units/Marc.png" },
    { type: "unit", name: "Peat", src: "units/Peat Pete.png" },
    { type: "unit", name: "Seagull", src: "units/Seagull Jonathan Johnathan.png" },
    { type: "unit", name: "Lone Rider", src: "units/Lone Rider Cowboy.png" },
    // Row 9
    { type: "blank" },
    { type: "unit", name: "Lulu", src: "units/Lulu.png" },
    { type: "unit", name: "Marie Poppo (Mixed)", src: "units/Marie Poppo (Mixed).png" },
    { type: "unit", name: "Kai", src: "units/Kai.png" },
    { type: "ui", name: "Gear", src: "units/Gear.png" },
    { type: "ui", name: "Return", src: "units/Return.png", link: "https://github.com/Hubcapp/wheres-the-oj" },
    { type: "unit", name: "Marc (Pilot)", src: "units/Marc (Pilot).png" },
    { type: "unit", name: "Flying Castle", src: "units/Flying Castle.png" },
    { type: "unit", name: "Merchant", src: "units/Scary Merchant.png" },
    { type: "blank" }
];